spring:
  profiles:
    active: dev
---
server:
  port: 8090
  servlet:
    context-path: /
spring:
  profiles: dev
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mycat配置主从数据库
    #url: jdbc:mysql://192.168.56.132:8066/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    #url: jdbc:mysql://192.168.2.54:3306/QA_NEW_ERP_VEDENG_COM?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  #配置SpringMVC视图解析器
#  mvc:
#    view:
#      prefix: classpath:/webapp/     # /默认代表根目录 src/main/webapp
#      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  aop:
    auto: true
node:
  port: 9000
  host: 0.0.0.1
  #配置springMVC视图解析器
#  mvc:         #引入mvn配置
#    view:
#      prefix: /WEB-INF/views/     # /默认代表根目录 src/main/webapp
#      suffix: .jsp
#  aop:
#    auto: true

#  #配置Redis连接信息
#  redis:
#    database: 0  # Redis数据库索引（默认为0）
#    host: 172.31.19.222 # Redis服务器地址
#    port: 8081  # Redis服务器连接端口
#    password:   # Redis服务器连接密码（默认为空）
#    jedis:
#      pool:
#        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8   # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 0  # 连接超时时间（毫秒)
#springBoot整合Mybatis
mybatis:
  #定义别名包,当程序自动映射是自动拼接
  type-aliases-package: com.jxx.pojo
  #引入映射文件
  mapper-locations: classpath:/mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

#引入logger日志
logging:
  level:
    #扫描的包路径
    com.jt.mapper: info

---
spring:
  profiles: prod
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mycat配置主从数据库
    #url: jdbc:mysql://192.168.56.132:8066/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    url: jdbc:mysql://192.168.1.53:3306/erp_ivedeng_com?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: erpuser
    password: neweu3453563
server:
  port: 8100
  servlet:
    context-path: /

node:
  port: 1000
  host: 1.1.1.1